### PR TITLE
fixed deprecation warnings for 10.12

### PR DESCRIPTION
**Pull request by robsaunders**

### CODE REVIEW

**Comment by wrl** [comment]
Hey, much obliged. I'd been putting off porting to 10.12. Do you know if this breaks building on 10.11 and lower?

**Comment by robsaunders** [comment]
The additions are supported but I'm not sure how far back they go... in my title here I said deprecation 'warning' but it's actually gotten to the point that it's an error and won't compile without these changes, so I'd imagine the changes go back some way.

**Comment by wrl** [comment]
Finally getting this merged with a stopgap for pre-10.12 building.

@robsaunders hit me up next time you're in Berlin, let's talk Rust and DSP.

**Comment by robsaunders** [comment]
sure, I'm in Berlin almost every year - my telegram is rob_saunders

**Pull request merged**
